app/posts/forms.py
# encoding: utf-8
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, SubmitField, HiddenField
from wtforms.fields.html5 import DateField
from wtforms.validators import Optional, Length, URL, Email, DataRequired
from flask_pagedown.fields import PageDownField

from app.models import Tag


class ProfileForm(FlaskForm):
    name = StringField(u'昵称', validators=[Optional(), Length(1, 64)])
    location = StringField(u'位置', validators=[Optional(), Length(1, 64)])
    bio = TextAreaField(u'简介')
    submit = SubmitField(u'提交')


class PostForm(FlaskForm):
    title = StringField(u'标题', validators=[DataRequired(), Length(1, 128)])
    description = TextAreaField(u'内容')
    # slides = StringField('Slides Embed Code (450 pixels wide)')
    # video = StringField('Video Embed Code (450 pixels wide)')
    tags = StringField(u'标签',
                        validators=[Length(1, 128)], description=u"多个标签请用空格分开")
    # venue_url = StringField(u'地点链接',
    #                         validators=[Optional(), Length(1, 128), URL()])
    # date = DateField(u'日期')
    submit_button = SubmitField(u'提交', id='submit_post')


    def from_model(self, post):
        self.title.data = post.title
        self.description.data = post.description


    def to_model(self, post):
        post.title = self.title.data
        post.description = self.description.data
        tag_list = self.tags.data.split(" ")
        for t in tag_list:
            tag = Tag.query.filter_by(name=t).first()    #first方法在没有结果时返回None, 这一点需要注意
            if not tag:
                tag = Tag(name=t)
            post.add_tag(tag)
        # post.tags

        # post.venue_url = self.venue_url.data
        # post.date =


class PresenterCommentForm(FlaskForm):
    reply_id = HiddenField()
    body = TextAreaField('Comment', validators=[DataRequired()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(1, 64)])
    email = StringField('Email', validators=[DataRequired(), Length(1, 64),
                                             Email()])
    body = TextAreaField('Comment', validators=[DataRequired()])
    notify = BooleanField('Notify when new comments are posted', default=True)
    submit = SubmitField(u'提交')

app/comments/__init__.py
from flask import Blueprint

comment = Blueprint('comment', __name__)

from . import routes

app/comments/routes.py
# encoding: utf-8
from flask import render_template, flash, redirect, url_for, abort,\
    request, current_app, g, jsonify
from flask_login import login_required, current_user
from .. import db
from ..models import  Message, Comment, User_Approve, Post
from . import comment


@comment.route('/post/<int:post_id>/reply_comment', methods=['POST'])
@login_required
def reply_comment(post_id):
    reply_id = request.form.get('reply_id', 0, type=int)
    content = request.form.get('content', '', type=str)
    parent_id = request.form.get('parent_id', '', type=int)
    parent_comment = Comment.query.get_or_404(parent_id)
    new_comment = Comment(body=content,
                              post_id=post_id, reply_id=reply_id,
                              author=current_user,
                              parent = parent_comment,
                              approved=True)
    # parent_comment.child_comments.append(new_comment)
    db.session.add(new_comment)
    # db.session.add(parent_comment)
    # db.session.add(parent_comment)
    db.session.commit()
    return jsonify(rs="olla")


@comment.route('/post/<int:post_id>/approve_comment', methods=['POST'])
@login_required
def approve(post_id):
    target_id = request.form.get('target_id', 0, type=int)
    target_type = request.form.get('target_type', '', type=str)
    is_approved = User_Approve.query.filter_by(target_id=target_id, target_type=target_type,
                              user_id=current_user.id,
                              approved=True).count()
    if is_approved < 1:
        new_approve = User_Approve(target_id=target_id, target_type=target_type,
                              user_id=current_user.id,
                              approved=True)
        comment = Comment.query.get(target_id)
        message = Message(sender=current_user.id, receiver=comment.author_id, action='approve comment',
                          target_id=comment.id, target_type="comment")

        db.session.add(new_approve)
        db.session.add(message)
        db.session.commit()
        rs = 1
    elif is_approved == 1:
        rs = 0
    else:
        db.session.query(User_Approve).filter_by(target_id=target_id, target_type=target_type,
                              user_id=current_user.id,
                              approved=True).delete()
        db.session.commit()
        rs = 0
    return jsonify(rs=rs)



@comment.route('/post/<int:post_id>/approve', methods=['POST'])
@login_required
def approve_post(post_id):
    target_id = request.form.get('target_id', 0, type=int)
    target_type = request.form.get('target_type', '', type=str)
    is_approved = User_Approve.query.filter_by(target_id=target_id, target_type=target_type,
                              user_id=current_user.id,
                              approved=True).count()
    if is_approved < 1:
        new_approve = User_Approve(target_id=target_id, target_type=target_type,
                              user_id=current_user.id,
                              approved=True)
        post = Post.query.get(target_id)
        message = Message(sender=current_user.id, receiver=post.user_id, action='approve post',
                          target_id=post.id, target_type="post")

        db.session.add(new_approve)
        db.session.add(message)
        db.session.commit()
        rs = 1
    elif is_approved == 1:
        rs = 0
    else:
        db.session.query(User_Approve).filter_by(target_id=target_id, target_type=target_type,
                              user_id=current_user.id,
                              approved=True).delete()
        db.session.commit()
        rs = 0
    return jsonify(rs=rs)

app/posts/__init__.py
from flask import Blueprint

posts = Blueprint('posts', __name__)

from . import routes

app/posts/routes.py
# encoding: utf-8
from flask import render_template, flash, redirect, url_for, abort,\
    request, current_app, g
from flask_login import login_required, current_user
from .. import db
from ..models import User, Post, Comment, post_tag, Message
# from ..emails import send_author_notification, send_comment_notification
from . import posts
from .forms import ProfileForm, PostForm, CommentForm, PresenterCommentForm


@posts.route('/')
# @login_required
def index():
    page = request.args.get('page', 1, type=int)
    if current_user.is_authenticated:
        pagination = current_user.followed_posts().paginate(
            page, per_page=current_app.config['TALKS_PER_PAGE'],
            error_out=False)
    else:
        pagination = Post.query.order_by(Post.date.desc()).paginate(
        page, per_page=current_app.config['TALKS_PER_PAGE'],
        error_out=False)
    post_list = pagination.items
    return render_template('posts/index.html', posts=post_list, read_only=True,
                           pagination=pagination)

@posts.route('/explore')
# @login_required
def explore():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.date.desc()).paginate(
        page, per_page=current_app.config['TALKS_PER_PAGE'],
        error_out=False)
    post_list = pagination.items
    return render_template('posts/index.html', posts=post_list, read_only=True,
                           pagination=pagination)


@posts.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    pagination = user.posts.order_by(Post.date.desc()).paginate(
        page, per_page=current_app.config['TALKS_PER_PAGE'],
        error_out=False)
    post_list = pagination.items
    if user == current_user:

        return render_template('posts/user.html', user=user, posts=post_list,
                           followed=len(list(user.followee))-1, followers=len(list(user.fans))-1,
                           pagination=pagination)
    return render_template('posts/user.html', user=user, posts=post_list,
                           pagination=pagination)


@posts.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = ProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.bio = form.bio.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash(u'您的信息已更新')
        return redirect(url_for('posts.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.bio.data = current_user.bio
    return render_template('posts/profile.html', form=form)


@posts.route('/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        print("post_tag count: {}".format(db.session.query(post_tag).all()))
        post = Post(author=current_user)
        form.to_model(post)
        db.session.add(post)
        db.session.commit()
        flash(u'发布成功')
        print("post_tag count: {}".format(db.session.query(post_tag).all()))
        return redirect(url_for('.index'))
    return render_template('posts/edit_post.html', form=form)


@posts.route('/post/<int:id>', methods=['GET', 'POST'])
def post(id):
    post = Post.query.get(id)
    comment = None
    if current_user.is_authenticated:
        form = PresenterCommentForm()
        if form.validate_on_submit():   # form post请求valid
            comment = Comment(body=form.body.data,
                              post=post, reply_id = int(form.data.get("reply_id")) if form.data.get("reply_id") else None,
                              author=current_user,
                              approved=True)
            # if comment.reply_id:
            #     message = Message(sender=current_user.id, receiver=comment.reply_user.id, action='reply comment',
            #                       target_id=comment.reply_id, target_type="comment")  # 给原评论作者的消息
            #     if comment.reply_user.id != post.user_id:
            #         msg = Message(sender=current_user.id, receiver=post.user_id, action='add comment',
            #                       target_id=post.id, target_type="post")  # 给原主题作者的消息
            #         db.session.add(msg)
            # else:
            #     message = Message(sender=current_user.id, receiver=post.user_id, action='add comment',
            #                       target_id=post.id, target_type="post")
            # db.session.add(comment)
            # db.session.add(message)
            # db.session.commit()
            # if comment.approved:
            #     # send_comment_notification(comment)
            #     flash('Your comment has been published.')
            # else:
            #     # send_author_notification(post)
            #     flash('Your comment will be published after it is reviewed by '
            #           'the presenter.')
            # return redirect(url_for('.post', id=post.id) + '#top')
    else:    # 未登录用户的发表评论
        form = CommentForm()
        if form.validate_on_submit():
            comment = Comment(body=form.body.data,
                              post=post,
                              author_name=form.name.data,
                              author_email=form.email.data,
                              approved=True)    # 之前站外用户的评论需要审查通过才会显示
    if comment:    #post请求则comment有数据，get请求则comment为None
        # if current_user.is_authenticated:
        sender = current_user.id if current_user.is_authenticated else None
        sender_email = None
        if not sender:
            sender_email = comment.author_email
        if comment.reply_id:
            message = Message(sender=sender, receiver=comment.reply_user.id, action='reply comment',
                              target_id=comment.reply_id, target_type="comment", sender_email=sender_email)   #给原评论作者的消息
            if comment.reply_user.id != post.user_id:
                msg = Message(sender=sender, receiver=post.user_id, action='add comment',
                                  target_id=post.id, target_type="post", sender_email=sender_email)           #给原主题作者的消息
                db.session.add(msg)
        else:
            message = Message(sender=sender, receiver=post.user_id, action='add comment',
                          target_id=post.id, target_type="post", sender_email=sender_email)

        # else:
        #     message = Message(sender=current_user.id, receiver=post.user_id, action='add comment',
        #                       target_id=post.id, target_type="post")

        db.session.add(message)
        db.session.add(comment)
        db.session.commit()
        if comment.approved:
            # send_comment_notification(comment)
            flash('Your comment has been published.')
        else:
            # send_author_notification(post)
            flash('Your comment will be published after it is reviewed by '
                  'the presenter.')
        return redirect(url_for('.post', id=post.id) + '#top')
    if post.author == current_user or \
            (current_user.is_authenticated and current_user.is_admin):
        comments_query = post.comments
    else:
        comments_query = post.approved_comments()  #Todo, fix
    page = request.args.get('page', 1, type=int)
    pagination = comments_query.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=current_app.config['COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items
    headers = {}
    if current_user.is_authenticated:
        headers['X-XSS-Protection'] = '0'
    return render_template('posts/post.html', post=post, form=form, read_only=True, show_full_content=True,
                           comments=comments, pagination=pagination),\
           200, headers


@posts.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_post(id):
    post = Post.query.get_or_404(id)
    if not current_user.is_admin and post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        form.to_model(post)
        db.session.add(post)
        db.session.commit()
        flash(u'修改成功')
        return redirect(url_for('.post', id=post.id))
    form.from_model(post)
    return render_template('posts/edit_post.html', form=form)


@posts.route('/moderate')
@login_required
def moderate():
    comments = current_user.for_moderation().order_by(Comment.timestamp.asc())
    return render_template('posts/moderate.html', comments=comments)


@posts.route('/moderate-admin')
@login_required
def moderate_admin():
    if not current_user.is_admin:
        abort(403)
    comments = Comment.for_moderation().order_by(Comment.timestamp.asc())
    return render_template('posts/moderate.html', comments=comments)


@posts.route('/unsubscribe/<token>')
def unsubscribe(token):
    post, email = Post.unsubscribe_user(token)
    if not post or not email:
        flash('Invalid unsubscribe token.')
        return redirect(url_for('posts.index'))
    # PendingEmail.remove(email)
    flash('You will not receive any more email notifications about this post.')
    return redirect(url_for('posts.post', id=post.id))


@posts.route('/follow/<username>')
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user is None:
        flash('User %s not found.' % username)
        return redirect(url_for('index'))
    if user == current_user:
        flash('You can\'t follow yourself.')
        return redirect(url_for('posts.user', username=username))
    u = current_user.follow(user)
    if u is None:
        flash('Cannot follow ' + username + '.')
        return redirect(url_for('posts.user', username=username))

app/templates/posts/_child_comments.html
<ul class="child-comments">
    {% if comment.children %}
        {% for child_comment in comment.children %}
            <li class="child-comment">
            <div>{{ child_comment.author.username }}: <br>
                {{ child_comment.body }}</div>
            <div class="comment-action">
                <span class="glyphicon glyphicon-thumbs-up"></span>
                <span class="glyphicon glyphicon-comment reply_comment"></span>
            </div>
            </li>
        {% endfor %}
    {% endif %}
</ul>

app/templates/posts/_comment.html
<p>
    {% if comment.author %}
        {% if index %}
        <span class="label label-primary">#{{ index }}</span>
        {% endif %}
        <a href="{{ url_for('.user', username=comment.author.username) }}">{{ comment.author.username }}</a>
    {% else %}
        {% if post.author == current_user or current_user.is_admin %}
            {% if not comment.approved %}
            <div id="moderate-{{ comment.id }}" class="pull-right">
                <a class="btn btn-primary api-approve" data-id="{{ comment.id }}" href="#"><span class="glyphicon glyphicon-ok"></span> Approve</a>
                <a class="btn btn-danger api-delete" data-id="{{ comment.id }}" href="#"><span class="glyphicon glyphicon-trash"></span> Delete</a>
            </div>
            <div id="approved-{{ comment.id }}" class="pull-right" style="display: none;">
                <span class="glyphicon glyphicon-ok"></span> <b>Approved</b>
            </div>
            <div id="deleted-{{ comment.id }}" class="pull-right" style="display: none;">
                <span class="glyphicon glyphicon-trash"></span> <b>Deleted</b>
            </div>
            {% endif %}
        {% endif %}
        {% if index %}
        <span class="label label-default">#{{ index }}</span>
        {% endif %}
        <b>{{ comment.author_name }}</b>
        {% if current_user.is_authenticated and (post.author == current_user or current_user.is_admin) %}
        (<a href="mailto:{{ comment.author_email }}">{{ comment.author_email }}</a>)
        {% endif %}
    {% endif %}
    {% if comment.reply_name %}
    reply to <a href="{{ url_for('.user', username=comment.reply_name) }}">{{ comment.reply_name }}</a>
    {% else %}
    commented
    {% endif %}
    {{ moment(comment.timestamp).fromNow() }}:
</p>
<div class="comment-body" data-comment-id={{ comment.id }} data-type="comment">
    {% if comment.body_html %}
    {{ comment.body_html | safe }}
    {% else %}
    {{ comment.body }}
    {% endif %}
    <div class="comment-action">
    <span class="glyphicon glyphicon-thumbs-up"></span>
        <span class="upvote-count">{{ comment.approve_count }}</span>
        <span class="separator">·</span>
    <span class="glyphicon glyphicon-comment reply_comment"></span>
    </div>
{#    {% include "post/_child_comments.html" %}#}

</div>

app/templates/posts/_comments.html
<ul class="comment-list">
{% if pagination %}
    {% set base_index = (pagination.page - 1) * pagination.per_page %}
{% else %}
    {% set base_index = 0 %}
{% endif %}
{% for comment in comments %}
    {% set index = loop.index + base_index %}
    <li class="comment">
        {% include "posts/_comment.html" %}
    </li>
{% endfor %}
</ul>

app/templates/posts/_post_header.html
<div class="post-header">
    {% if post.tags %}
    {% for tag in post.tags %}
    <a href="{{ url_for('tag.tag_profile', tag_name=tag.name) }}" class="tag">{{ tag.name }}</a>
    {% endfor %}
    {% endif %}
    {% if  not read_only %}
    {% if post.author == current_user %}
    <a class="btn btn-primary pull-right" href="{{ url_for('posts.edit_post', id=post.id) }}">Edit</a>
    {% elif current_user.is_admin %}
    <a class="btn btn-danger pull-right" href="{{ url_for('posts.edit_post', id=post.id) }}">Edit</a>
    {% endif %}
    {% endif %}
    <a href="{{ url_for('posts.post', id=post.id) }}"><h3>{{ post.title }}</h3></a>
    {% if show_full_content %}
        {{ post.description|safe }}
    {% else %}
{#    {{ post.description|safe }}#}
    {% endif %}
    <div class="pull-right" data-post-id={{ post.id }}>
        <span class="glyphicon glyphicon-heart"></span>
<span class="approve-count label label-default">{{ post.approve_count }}</span>
        <a href="{{ url_for('posts.post', id=post.id) }}#comments"><span class="label label-default">Comments: {{ post.approved_comments().count() }}</span></a>
    </div>

    <p>
        Presented by <a href="{{ url_for('posts.user', username=post.author.username) }}">{{ post.author.username }}</a> at
        on {{ moment(post.date, local=True).format('LL') }}.
    </p>
</div>

app/templates/posts/_posts.html
<ul class="post-list">
{% for post in posts %}
    <li class="post">
    {% include "posts/_post_header.html" %}
    </li>
{% endfor %}
</ul>

app/templates/posts/edit_post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>你想说些什么?</h1>
</div>
{{ wtf.quick_form(form,id="create_post_form") }}
{% endblock %}

app/templates/posts/index.html
{% extends "base.html" %}

{% block page_content %}
{% include "posts/_posts.html" %}
{% if posts %}
<ul class="pager">
    {% if pagination.has_prev %}
    <li class="previous"><a href="{{ url_for('posts.index', page=pagination.prev_num) }}">&larr; Newer</a></li>
    {% else %}
    <li class="previous disabled"><a href="#">&larr; Newer</a></li>
    {% endif %}
    {% if pagination.has_next %}
    <li class="next"><a href="{{ url_for('posts.index', page=pagination.next_num) }}">Older &rarr;</a></li>
    {% else %}
    <li class="next disabled"><a href="#">Older &rarr;</a></li>
    {% endif %}
</ul>
{% endif %}
<p> hey you.</p>
{% endblock %}

app/templates/posts/moderate.html
{% extends "base.html" %}

{% block page_content %}
<h2>Comment moderation</h2>
<ul class="comment-list">
{% for comment in comments %}
    {% set post = comment.post %}
    <li class="comment">
        <p>In <a href="{{ url_for('post.post', id=post.id) }}">{{ post.title }}</a></p>
        {% include "post/_comment.html" %}
    </li>
{% endfor %}
</ul>
{% endblock %}

{% block scripts %}
{{ super() }}
{% include "_api_client.html" %}
{% endblock %}

app/templates/posts/post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

<style>
a:hover
{
background-color:red;
}
</style>

{% block page_content %}
<div class="page-header">
    {% include "posts/_post_header.html" %}
</div>
<div class="post-body">
    {% if post.video %}
    <div class="post-video">
    {{ post.video | safe }}
    </div>
    {% endif %}
    {% if post.slides %}
    <div class="post-slides">
    {{ post.slides | safe }}
    </div>
    {% endif %}
</div>
{% if comments %}
<h3 id="comments">Comments</h3>
{% include "posts/_comments.html" %}
<ul class="pager">
    {% if pagination.has_prev %}
    <li class="previous"><a href="{{ url_for('posts.post', id=post.id, page=pagination.prev_num) }}#comments">&larr; Older</a></li>
    {% else %}
    <li class="previous disabled"><a href="#">&larr; Older</a></li>
    {% endif %}
    {% if pagination.has_next %}
    <li class="next"><a href="{{ url_for('posts.post', id=post.id, page=pagination.next_num) }}#comments">Newer &rarr;</a></li>
    {% else %}
    <li class="next disabled"><a href="#">Newer &rarr;</a></li>
    {% endif %}
</ul>
{% endif %}
<h3 id="comment-form">Write a comment</h3>
{{ wtf.quick_form(form, action='#comment-form') }}
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/autosize.js/1.18.1/jquery.autosize.min.js"></script>
<script>
    $(document).ready(function() {
        $('#flask-pagedown-body').autosize();
    });
$(".reply_comment").click(function(event) {
{#    alert("lala"); todo: 应该先检查有没有已经打开的评论框,如果有,remove,#}
    event.preventDefault();
    var comment_body = $(event.target).closest(".comment-body");
    comment_id = comment_body.attr("data-comment-id");
{#    alert(comment_id);#}
    $("input#reply_id").attr("value", comment_id);
{#    $(".flask-pagedown-input").attr("reply-id", comment_id);#}
    $('html, body').animate({
            scrollTop: $("#body").offset().top
        }, 500, function() {
            $("#body").focus();
        });

{#    alert("tt");#}

{#    var comment_box = $("body").find(".frm_add");#}
{#    console.log(comment_box);#}
{#    comment_box.remove();#}
{##}
{#    var comment_body = $(event.target).closest(".comment-body");#}
{#    comment_id = comment_body.attr("data-comment-id");#}
{#    url = "/comment/" + comment_id;#}
{#    comment_body.append('<form class="frm_add"><textarea cols="10" rows="3" class="form-control comment-message" placeholder="Whats on your mind ?"></textarea>' +#}
{#            '<div class="comment-action" style="height: 28px; position: relative;"> \#}
{#        <button class="btn btn-default btn-cancel" style="right: 70px; position: absolute;" type="button">取消</button> \#}
{#        <button class="btn btn-primary btn-comment" style="position: absolute; right: 0;" type="submit">评论</button> \#}
{#    </div></form>');#}
});


$("body").on("submit", ".frm_add", function (event){

    event.preventDefault();
{#    alert("gaga");  注意, comment-message在一个页面只显示一个#}

    var child_comments = $(event.target).parent().find(".child-comments");
    var parent_comment_id = $(event.target).parent().attr("data-comment-id");
    var input = $(".comment-message").val();
{#    console.log(child_comments);#}
    var current_url = window.location.pathname;
    $(this).closest("form").remove();
    child_comments.append('<p id="comment-form">' + input  + '</p>');

   /* $.ajax function will go here to save row */
   $.ajax({
    url : current_url + "/reply_comment",
    type: "POST",
    data : {parent_id: parent_comment_id, content: input, reply_id: parent_comment_id},
    success: function(data, textStatus, jqXHR)
    {
        console.log(data);
    },
    error: function (jqXHR, textStatus, errorThrown)
    {

    }
});
});

$('.glyphicon-thumbs-up').click(function(event) {
{#    event.preventDefault();#}

    var comment_body = $(event.target).closest(".comment-body");
    var target_id = comment_body.attr("data-comment-id");
    var target_type = comment_body.attr("data-type");
    var current_url = window.location.pathname;
    $.ajax({
    url : current_url + "/approve_comment",
    type: "POST",
    data : {target_id: target_id, target_type: target_type},
    success: function(data, textStatus, jqXHR)
    {
        console.log(data);
        if (data.rs == 1) {
            var element = comment_body.find(".upvote-count");
{#            console.log(element);#}
            var approve_count = parseInt(element.text()) + 1;
            element.text(approve_count);
        }
    },
    error: function (jqXHR, textStatus, errorThrown)
    {}
    });
});


$('.glyphicon-heart').click(function(event) {

{#    alert("ni");#}

{#    var comment_body = $(event.target).closest(".comment-body");#}
{#    var target_id = comment_body.attr("data-comment-id");#}
{#    var target_type = comment_body.attr("data-type");#}
{#    var current_url = window.location.pathname;#}
{#    $.ajax({#}
{#    url : current_url + "/approve",#}
{#    type: "POST",#}
{#    data : {target_id: target_id, target_type: target_type},#}
{#    success: function(data, textStatus, jqXHR)#}
{#    {#}
{#        console.log(data);#}
{#        if (data.rs == 1) {#}
{#            var element = comment_body.find(".upvote-count");#}
{#            var approve_count = parseInt(element.text()) + 1;#}
{#            element.text(approve_count);#}
{#        }#}
{#    },#}
{#    error: function (jqXHR, textStatus, errorThrown)#}
{#    {}#}
{#    });#}
});

</script>
{% include "_api_client.html" %}
{% endblock %}

app/templates/posts/profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>编辑个人信息</h1>
</div>
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/posts/user.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-header user-profile">
    <div class="user-avatar"><img src="{{ user.gravatar(128) }}"></div>
    <h1>{{ user.username }}</h1>
    {% if current_user == user %}
        <a class="btn btn-default pull-right" href="{{ url_for('posts.profile') }}">Edit Profile</a>
        <p>已关注{{ followed }}人</p>
        <p>关注者{{ followers }}人</p>
    {% elif not current_user.is_following(user) %}
        <a href="{{ url_for('posts.follow', username=user.username) }}">关注</a>
    {% else %}
        <a href="{{ url_for('posts.unfollow', username=user.username) }}">取消关注</a>
    {% endif %}

    <p>
        {% if user.name %}{{ user.name }}<br>{% endif %}
        {% if user.location %}<a href="http://maps.google.com?q={{ user.location }}">{{ user.location }}</a><br>{% endif %}
    </p>
    {% if user.bio %}<p>{{ user.bio }}</p>{% endif %}
</div>
{% include "posts/_posts.html" %}
{% if posts %}
<ul class="pager">
    {% if pagination.has_prev %}
    <li class="previous"><a href="{{ url_for('posts.user', username=user.username, page=pagination.prev_num) }}">&larr; Newer</a></li>
    {% else %}
    <li class="previous disabled"><a href="#">&larr; Newer</a></li>
    {% endif %}
    {% if pagination.has_next %}
    <li class="next"><a href="{{ url_for('posts.user', username=user.username, page=pagination.next_num) }}">Older &rarr;</a></li>
    {% else %}
    <li class="next disabled"><a href="#">Older &rarr;</a></li>
    {% endif %}
</ul>
{% endif %}
{% endblock %}